# -*- coding: utf-8 -*-
"""Project Brain Tumor Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hljAYpR8kYK2GPElTFFSLOM2AAtsopz

**Importing the libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from pandas import plotting
import io

"""**Importing dataset**"""

from google.colab import files
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['Brain_Tumor.csv']))
df.head()

print('Rows and columns :',df.shape)

df.describe()

"""**Checking and Dropping null values**"""

df.isnull().sum()

"""**Value Count**"""

df['Class'].value_counts()

"""**Visualize the value count**"""

sns.countplot(df['Class'],label = 'count')

"""**Pairplot**"""

import warnings
warnings.filterwarnings('ignore')

sns.pairplot(df, hue = 'Class')

"""**Heatmap**"""

plt.figure(figsize = (11,11))
sns.heatmap(df.corr(), annot = True,linewidths=0.5,cmap='Greens')
plt.show()

plt.figure(figsize = (16,8))

plt.grid(True)
plt.xlabel('Homogeneity')
plt.ylabel('Class')
plt.plot(df['Class'])
plt.show()

"""**Barplot Class vs Mean**"""

fig = plt.figure(figsize = (7,5))
sns.barplot(data = df, x= 'Class', y='Mean')

"""**Barplot Class vs Variance**"""

fig = plt.figure(figsize = (7,5))
sns.barplot(data = df, x= 'Class', y='Variance')

"""**Displot Energy vs Class**"""

sns.displot(df, x = 'Energy', col = 'Class', kde = True)

"""**Displot Dissimilarity vs Class**"""

sns.displot(df, x = 'Dissimilarity', col = 'Class', kde = True)

"""**Splitting of dataset**"""

from sklearn.model_selection import train_test_split

X = df.iloc[:, 2:15].values
y = df.iloc[:, 1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=0)

"""**Preprocessing of dataset**"""

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""**Dimensions**"""

print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("Y_train shape : ",y_train.shape)
print("Y_test shape : ",y_test.shape)

"""**Using KNN**"""

from sklearn.neighbors import KNeighborsClassifier

KNN = KNeighborsClassifier(n_neighbors = 5)
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

"""**Using Linear Regression**"""

from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

"""**Using Support Vector Classifier (Linear SVC)**"""

from sklearn.svm import SVC, LinearSVC

SVM = LinearSVC()
SVM.fit(X_train, y_train)
y_pred = SVM.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

"""**Using Random Forest**"""

from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier(n_estimators=200)
RFC.fit(X_train, y_train)
y_pred = RFC.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

"""Using Decision Tree**"""

from sklearn.tree import DecisionTreeClassifier

DTC = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DTC.fit(X_train, y_train)
y_pred = DTC.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

"""**Using Support Vector Classifier**"""

from sklearn.svm import SVC

SVC = SVC()
SVC.fit(X_train, y_train)
y_pred = SVC.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

"""**Using Naive Bayes**"""

from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)

from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score

print('Accuracy score : ',accuracy_score(y_test, y_pred)*100)
print('Precision Score : ',precision_score(y_test, y_pred)*100)
print('Recall Score : ',recall_score(y_test, y_pred)*100)
print('F1 score : ',f1_score(y_test, y_pred)*100)
print('Confusion Matrix: ',confusion_matrix(y_test,y_pred), sep = '\n')

